import sys
from PyQt5 import QtCore, QtGui, QtWidgets

import CUHA_logo
import font


class quiz_main(object):
    def quiz_main_setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1377, 860)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Quiz_Label = QtWidgets.QLabel(self.centralwidget)
        self.Quiz_Label.setGeometry(QtCore.QRect(80, 30, 1130, 140))
        self.fontDB = QtGui.QFontDatabase()
        self.fontDB.addApplicationFont(":/font/KoPubWorld Dotum Bold.ttf")
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.Quiz_Label.setFont(font)
        self.Quiz_Label.setScaledContents(True)
        self.Quiz_Label.setObjectName("Quiz_Label")
        self.Sel_1 = QtWidgets.QLabel(self.centralwidget)
        self.Sel_1.setGeometry(QtCore.QRect(130, 230, 1200, 80))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.Sel_1.setFont(font)
        self.Sel_1.setScaledContents(False)
        self.Sel_1.setObjectName("Sel_1")
        self.Logo = QtWidgets.QLabel(self.centralwidget)
        self.Logo.setGeometry(QtCore.QRect(50, 660, 171, 161))
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap(":/cuha_logo/CUHA_logo.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setObjectName("Logo")
        self.Btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_1.setGeometry(QtCore.QRect(50, 240, 61, 61))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_1.setFont(font)
        self.Btn_1.setObjectName("Btn_1")
        self.Btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_2.setGeometry(QtCore.QRect(50, 390, 61, 61))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_2.setFont(font)
        self.Btn_2.setObjectName("Btn_2")
        self.Btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_3.setGeometry(QtCore.QRect(50, 540, 61, 61))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_3.setFont(font)
        self.Btn_3.setObjectName("Btn_3")
        self.Sel_2 = QtWidgets.QLabel(self.centralwidget)
        self.Sel_2.setGeometry(QtCore.QRect(130, 380, 1200, 80))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.Sel_2.setFont(font)
        self.Sel_2.setScaledContents(False)
        self.Sel_2.setObjectName("Sel_2")
        self.Sel_3 = QtWidgets.QLabel(self.centralwidget)
        self.Sel_3.setGeometry(QtCore.QRect(130, 530, 1200, 80))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.Sel_3.setFont(font)
        self.Sel_3.setScaledContents(False)
        self.Sel_3.setObjectName("Sel_3")
        self.Btn_Next = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Next.setGeometry(QtCore.QRect(1100, 730, 141, 71))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Next.setFont(font)
        self.Btn_Next.setObjectName("Btn_Next")
        self.Btn_Prev = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Prev.setGeometry(QtCore.QRect(900, 730, 141, 71))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Prev.setFont(font)
        self.Btn_Prev.setObjectName("Btn_Prev")
        self.Current_num = QtWidgets.QLabel(self.centralwidget)
        self.Current_num.setGeometry(QtCore.QRect(710, 740, 61, 51))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.Current_num.setFont(font)
        self.Current_num.setScaledContents(False)
        self.Current_num.setAlignment(QtCore.Qt.AlignCenter)
        self.Current_num.setObjectName("Current_num")
        self.Slash = QtWidgets.QLabel(self.centralwidget)
        self.Slash.setGeometry(QtCore.QRect(770, 740, 20, 51))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.Slash.setFont(font)
        self.Slash.setAlignment(QtCore.Qt.AlignCenter)
        self.Slash.setObjectName("Slash")
        self.Total_num = QtWidgets.QLabel(self.centralwidget)
        self.Total_num.setGeometry(QtCore.QRect(790, 740, 61, 51))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.Total_num.setFont(font)
        self.Total_num.setScaledContents(False)
        self.Total_num.setAlignment(QtCore.Qt.AlignCenter)
        self.Total_num.setObjectName("Total_num")
        self.info_Label = QtWidgets.QLabel(self.centralwidget)
        self.info_Label.setGeometry(QtCore.QRect(230, 740, 451, 51))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.info_Label.setFont(font)
        self.info_Label.setObjectName("info_Label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "정보 보안 교육 프로그램"))
        self.Quiz_Label.setText(_translate("MainWindow", "\n문제 1. 다음 중 가장 안전하게 비밀번호를 설정한 사람은?"))
        self.Sel_1.setText(_translate("MainWindow", "쉽게 기억할 수 있도록 모든 사이트의 비밀번호를 동일하게 설정한 나연"))
        self.Btn_1.setText(_translate("MainWindow", "1"))
        self.Btn_2.setText(_translate("MainWindow", "2"))
        self.Btn_3.setText(_translate("MainWindow", "3"))
        self.Sel_2.setText(_translate("MainWindow", "쉽게 기억할 수 있도록 본인의 이름과 생년월일로 비밀번호를 설정한 정연"))
        self.Sel_3.setText(_translate("MainWindow", "남들이 쉽게 유추할 수 없는 비밀번호를 설정하고, 모든 사이트의 비밀번호를 다르게 설정한 다현"))
        self.Btn_Next.setText(_translate("MainWindow", "->"))
        self.Btn_Prev.setText(_translate("MainWindow", "<-"))
        self.Current_num.setText(_translate("MainWindow", "1"))
        self.Slash.setText(_translate("MainWindow", "/"))
        self.Total_num.setText(_translate("MainWindow", "20"))
        self.info_Label.setText(_translate("MainWindow", "2019 정보 보호 교육 프로그램"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = quiz_main()
    ui.quiz_main_setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
