import sys
from PyQt5 import QtCore, QtGui, QtWidgets

import CUHA_logo
import font


class quiz_result(object):
    def quiz_result_setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1307, 839)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Logo = QtWidgets.QLabel(self.centralwidget)
        self.Logo.setGeometry(QtCore.QRect(10, 550, 251, 241))
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap(":/cuha_logo/CUHA_logo.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setObjectName("Logo")
        self.h_line_1 = QtWidgets.QFrame(self.centralwidget)
        self.h_line_1.setGeometry(QtCore.QRect(0, 90, 1391, 20))
        self.h_line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.h_line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.h_line_1.setObjectName("h_line_1")
        self.finish_label = QtWidgets.QLabel(self.centralwidget)
        self.finish_label.setGeometry(QtCore.QRect(440, 10, 421, 71))
        self.fontDB = QtGui.QFontDatabase()
        self.fontDB.addApplicationFont(":/font/KoPubWorld Dotum Bold.ttf")
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.finish_label.setFont(font)
        self.finish_label.setObjectName("finish_label")
        self.h_line_2 = QtWidgets.QFrame(self.centralwidget)
        self.h_line_2.setGeometry(QtCore.QRect(0, 300, 1391, 20))
        self.h_line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.h_line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.h_line_2.setObjectName("h_line_2")
        self.h_line_3 = QtWidgets.QFrame(self.centralwidget)
        self.h_line_3.setGeometry(QtCore.QRect(0, 510, 1391, 20))
        self.h_line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.h_line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.h_line_3.setObjectName("h_line_3")
        self.v_line_10 = QtWidgets.QFrame(self.centralwidget)
        self.v_line_10.setGeometry(QtCore.QRect(260, 520, 20, 300))
        self.v_line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.v_line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.v_line_10.setObjectName("v_line_10")
        self.h_line_4 = QtWidgets.QFrame(self.centralwidget)
        self.h_line_4.setGeometry(QtCore.QRect(0, 810, 1391, 20))
        self.h_line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.h_line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.h_line_4.setObjectName("h_line_4")
        self.v_line_1 = QtWidgets.QFrame(self.centralwidget)
        self.v_line_1.setGeometry(QtCore.QRect(125, 100, 20, 421))
        self.v_line_1.setFrameShape(QtWidgets.QFrame.VLine)
        self.v_line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.v_line_1.setObjectName("v_line_1")
        self.v_line_2 = QtWidgets.QFrame(self.centralwidget)
        self.v_line_2.setGeometry(QtCore.QRect(260, 100, 20, 421))
        self.v_line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.v_line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.v_line_2.setObjectName("v_line_2")
        self.v_line_3 = QtWidgets.QFrame(self.centralwidget)
        self.v_line_3.setGeometry(QtCore.QRect(390, 100, 20, 421))
        self.v_line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.v_line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.v_line_3.setObjectName("v_line_3")
        self.v_line_4 = QtWidgets.QFrame(self.centralwidget)
        self.v_line_4.setGeometry(QtCore.QRect(520, 100, 20, 421))
        self.v_line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.v_line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.v_line_4.setObjectName("v_line_4")
        self.v_line_5 = QtWidgets.QFrame(self.centralwidget)
        self.v_line_5.setGeometry(QtCore.QRect(650, 100, 20, 421))
        self.v_line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.v_line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.v_line_5.setObjectName("v_line_5")
        self.v_line_6 = QtWidgets.QFrame(self.centralwidget)
        self.v_line_6.setGeometry(QtCore.QRect(780, 100, 20, 421))
        self.v_line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.v_line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.v_line_6.setObjectName("v_line_6")
        self.v_line_7 = QtWidgets.QFrame(self.centralwidget)
        self.v_line_7.setGeometry(QtCore.QRect(910, 100, 20, 421))
        self.v_line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.v_line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.v_line_7.setObjectName("v_line_7")
        self.v_line_8 = QtWidgets.QFrame(self.centralwidget)
        self.v_line_8.setGeometry(QtCore.QRect(1040, 100, 20, 421))
        self.v_line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.v_line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.v_line_8.setObjectName("v_line_8")
        self.v_line_9 = QtWidgets.QFrame(self.centralwidget)
        self.v_line_9.setGeometry(QtCore.QRect(1170, 100, 20, 421))
        self.v_line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.v_line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.v_line_9.setObjectName("v_line_9")
        self.h_line_5 = QtWidgets.QFrame(self.centralwidget)
        self.h_line_5.setGeometry(QtCore.QRect(0, 140, 1391, 20))
        self.h_line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.h_line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.h_line_5.setObjectName("h_line_5")
        self.h_line_6 = QtWidgets.QFrame(self.centralwidget)
        self.h_line_6.setGeometry(QtCore.QRect(0, 350, 1391, 20))
        self.h_line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.h_line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.h_line_6.setObjectName("h_line_6")
        self.v_line_11 = QtWidgets.QFrame(self.centralwidget)
        self.v_line_11.setGeometry(QtCore.QRect(650, 520, 20, 300))
        self.v_line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.v_line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.v_line_11.setObjectName("v_line_11")
        self.total_label = QtWidgets.QLabel(self.centralwidget)
        self.total_label.setGeometry(QtCore.QRect(440, 550, 201, 251))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(80)
        font.setBold(True)
        font.setWeight(75)
        self.total_label.setFont(font)
        self.total_label.setAlignment(QtCore.Qt.AlignCenter)
        self.total_label.setObjectName("total_label")
        self.score_label = QtWidgets.QLabel(self.centralwidget)
        self.score_label.setGeometry(QtCore.QRect(290, 550, 121, 251))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(80)
        font.setBold(True)
        font.setWeight(75)
        self.score_label.setFont(font)
        self.score_label.setAlignment(QtCore.Qt.AlignCenter)
        self.score_label.setObjectName("score_label")
        self.guide_label = QtWidgets.QLabel(self.centralwidget)
        self.guide_label.setGeometry(QtCore.QRect(670, 530, 621, 271))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.guide_label.setFont(font)
        self.guide_label.setObjectName("guide_label")
        self.num_first_line = QtWidgets.QLabel(self.centralwidget)
        self.num_first_line.setGeometry(QtCore.QRect(0, 110, 1291, 31))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.num_first_line.setFont(font)
        self.num_first_line.setObjectName("num_first_line")
        self.num_second_line = QtWidgets.QLabel(self.centralwidget)
        self.num_second_line.setGeometry(QtCore.QRect(0, 320, 1291, 31))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.num_second_line.setFont(font)
        self.num_second_line.setObjectName("num_second_line")
        self.q_1_btn = QtWidgets.QPushButton(self.centralwidget)
        self.q_1_btn.setGeometry(QtCore.QRect(-1, 147, 136, 163))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(80)
        font.setBold(True)
        font.setWeight(75)
        self.q_1_btn.setFont(font)
        self.q_1_btn.setObjectName("q_1_btn")
        self.q_1_btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.q_1_btn_2.setGeometry(QtCore.QRect(133, 147, 137, 163))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(80)
        font.setBold(True)
        font.setWeight(75)
        self.q_1_btn_2.setFont(font)
        self.q_1_btn_2.setObjectName("q_1_btn_2")
        self.q_1_btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.q_1_btn_3.setGeometry(QtCore.QRect(268, 147, 133, 163))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(80)
        font.setBold(True)
        font.setWeight(75)
        self.q_1_btn_3.setFont(font)
        self.q_1_btn_3.setObjectName("q_1_btn_3")
        self.q_1_btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.q_1_btn_4.setGeometry(QtCore.QRect(398, 147, 133, 163))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(80)
        font.setBold(True)
        font.setWeight(75)
        self.q_1_btn_4.setFont(font)
        self.q_1_btn_4.setObjectName("q_1_btn_4")
        self.q_1_btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.q_1_btn_5.setGeometry(QtCore.QRect(528, 147, 133, 163))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(80)
        font.setBold(True)
        font.setWeight(75)
        self.q_1_btn_5.setFont(font)
        self.q_1_btn_5.setObjectName("q_1_btn_5")
        self.q_1_btn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.q_1_btn_6.setGeometry(QtCore.QRect(658, 147, 133, 163))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(80)
        font.setBold(True)
        font.setWeight(75)
        self.q_1_btn_6.setFont(font)
        self.q_1_btn_6.setObjectName("q_1_btn_6")
        self.q_1_btn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.q_1_btn_7.setGeometry(QtCore.QRect(788, 147, 133, 163))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(80)
        font.setBold(True)
        font.setWeight(75)
        self.q_1_btn_7.setFont(font)
        self.q_1_btn_7.setObjectName("q_1_btn_7")
        self.q_1_btn_8 = QtWidgets.QPushButton(self.centralwidget)
        self.q_1_btn_8.setGeometry(QtCore.QRect(918, 147, 133, 163))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(80)
        font.setBold(True)
        font.setWeight(75)
        self.q_1_btn_8.setFont(font)
        self.q_1_btn_8.setObjectName("q_1_btn_8")
        self.q_1_btn_9 = QtWidgets.QPushButton(self.centralwidget)
        self.q_1_btn_9.setGeometry(QtCore.QRect(1048, 147, 133, 163))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(80)
        font.setBold(True)
        font.setWeight(75)
        self.q_1_btn_9.setFont(font)
        self.q_1_btn_9.setObjectName("q_1_btn_9")
        self.q_1_btn_10 = QtWidgets.QPushButton(self.centralwidget)
        self.q_1_btn_10.setGeometry(QtCore.QRect(1178, 147, 133, 163))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(80)
        font.setBold(True)
        font.setWeight(75)
        self.q_1_btn_10.setFont(font)
        self.q_1_btn_10.setObjectName("q_1_btn_10")
        self.q_1_btn_11 = QtWidgets.QPushButton(self.centralwidget)
        self.q_1_btn_11.setGeometry(QtCore.QRect(-1, 357, 136, 163))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(80)
        font.setBold(True)
        font.setWeight(75)
        self.q_1_btn_11.setFont(font)
        self.q_1_btn_11.setObjectName("q_1_btn_11")
        self.q_1_btn_12 = QtWidgets.QPushButton(self.centralwidget)
        self.q_1_btn_12.setGeometry(QtCore.QRect(133, 357, 137, 163))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(80)
        font.setBold(True)
        font.setWeight(75)
        self.q_1_btn_12.setFont(font)
        self.q_1_btn_12.setObjectName("q_1_btn_12")
        self.q_1_btn_13 = QtWidgets.QPushButton(self.centralwidget)
        self.q_1_btn_13.setGeometry(QtCore.QRect(268, 357, 133, 163))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(80)
        font.setBold(True)
        font.setWeight(75)
        self.q_1_btn_13.setFont(font)
        self.q_1_btn_13.setObjectName("q_1_btn_13")
        self.q_1_btn_14 = QtWidgets.QPushButton(self.centralwidget)
        self.q_1_btn_14.setGeometry(QtCore.QRect(398, 357, 133, 163))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(80)
        font.setBold(True)
        font.setWeight(75)
        self.q_1_btn_14.setFont(font)
        self.q_1_btn_14.setObjectName("q_1_btn_14")
        self.q_1_btn_15 = QtWidgets.QPushButton(self.centralwidget)
        self.q_1_btn_15.setGeometry(QtCore.QRect(528, 357, 133, 163))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(80)
        font.setBold(True)
        font.setWeight(75)
        self.q_1_btn_15.setFont(font)
        self.q_1_btn_15.setObjectName("q_1_btn_15")
        self.q_1_btn_16 = QtWidgets.QPushButton(self.centralwidget)
        self.q_1_btn_16.setGeometry(QtCore.QRect(658, 357, 133, 163))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(80)
        font.setBold(True)
        font.setWeight(75)
        self.q_1_btn_16.setFont(font)
        self.q_1_btn_16.setObjectName("q_1_btn_16")
        self.q_1_btn_17 = QtWidgets.QPushButton(self.centralwidget)
        self.q_1_btn_17.setGeometry(QtCore.QRect(788, 357, 133, 163))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(80)
        font.setBold(True)
        font.setWeight(75)
        self.q_1_btn_17.setFont(font)
        self.q_1_btn_17.setObjectName("q_1_btn_17")
        self.q_1_btn_18 = QtWidgets.QPushButton(self.centralwidget)
        self.q_1_btn_18.setGeometry(QtCore.QRect(918, 357, 133, 163))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(80)
        font.setBold(True)
        font.setWeight(75)
        self.q_1_btn_18.setFont(font)
        self.q_1_btn_18.setObjectName("q_1_btn_18")
        self.q_1_btn_19 = QtWidgets.QPushButton(self.centralwidget)
        self.q_1_btn_19.setGeometry(QtCore.QRect(1048, 357, 133, 163))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(80)
        font.setBold(True)
        font.setWeight(75)
        self.q_1_btn_19.setFont(font)
        self.q_1_btn_19.setObjectName("q_1_btn_19")
        self.q_1_btn_20 = QtWidgets.QPushButton(self.centralwidget)
        self.q_1_btn_20.setGeometry(QtCore.QRect(1178, 357, 133, 163))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(80)
        font.setBold(True)
        font.setWeight(75)
        self.q_1_btn_20.setFont(font)
        self.q_1_btn_20.setObjectName("q_1_btn_20")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "정보 보안 교육 프로그램"))
        self.finish_label.setText(_translate("MainWindow", "수고하셨습니다!"))
        self.total_label.setText(_translate("MainWindow", "/ 20"))
        self.score_label.setText(_translate("MainWindow", "0"))
        self.guide_label.setText(_translate("MainWindow", "O X 버튼을 클릭하여 \n"
"문제 해설을 확인하세요!"))
        self.num_first_line.setText(_translate("MainWindow", "      1            2           3           4           5           6           7           8           9           10"))
        self.num_second_line.setText(_translate("MainWindow", "     11          12         13         14         15          16         17         18         19          20"))
        self.q_1_btn.setText(_translate("MainWindow", "O"))
        self.q_1_btn_2.setText(_translate("MainWindow", "O"))
        self.q_1_btn_3.setText(_translate("MainWindow", "O"))
        self.q_1_btn_4.setText(_translate("MainWindow", "O"))
        self.q_1_btn_5.setText(_translate("MainWindow", "O"))
        self.q_1_btn_6.setText(_translate("MainWindow", "O"))
        self.q_1_btn_7.setText(_translate("MainWindow", "O"))
        self.q_1_btn_8.setText(_translate("MainWindow", "O"))
        self.q_1_btn_9.setText(_translate("MainWindow", "O"))
        self.q_1_btn_10.setText(_translate("MainWindow", "O"))
        self.q_1_btn_11.setText(_translate("MainWindow", "O"))
        self.q_1_btn_12.setText(_translate("MainWindow", "O"))
        self.q_1_btn_13.setText(_translate("MainWindow", "O"))
        self.q_1_btn_14.setText(_translate("MainWindow", "O"))
        self.q_1_btn_15.setText(_translate("MainWindow", "O"))
        self.q_1_btn_16.setText(_translate("MainWindow", "O"))
        self.q_1_btn_17.setText(_translate("MainWindow", "O"))
        self.q_1_btn_18.setText(_translate("MainWindow", "O"))
        self.q_1_btn_19.setText(_translate("MainWindow", "O"))
        self.q_1_btn_20.setText(_translate("MainWindow", "O"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = quiz_result()
    ui.quiz_result_setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
