import sys
from PyQt5 import QtCore, QtGui, QtWidgets

import CUHA_logo
import font


class quiz_solution(object):
    def quiz_solution_setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1307, 839)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Logo = QtWidgets.QLabel(self.centralwidget)
        self.Logo.setGeometry(QtCore.QRect(0, 0, 161, 161))
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap(":/cuha_logo/CUHA_logo.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setObjectName("Logo")
        self.sol_q = QtWidgets.QLabel(self.centralwidget)
        self.sol_q.setGeometry(QtCore.QRect(170, 10, 1061, 131))
        self.fontDB = QtGui.QFontDatabase()
        self.fontDB.addApplicationFont(":/font/KoPubWorld Dotum Bold.ttf")
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.sol_q.setFont(font)
        self.sol_q.setTextFormat(QtCore.Qt.AutoText)
        self.sol_q.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sol_q.setObjectName("sol_q")
        self.my_answer = QtWidgets.QLabel(self.centralwidget)
        self.my_answer.setGeometry(QtCore.QRect(100, 180, 21, 41))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.my_answer.setFont(font)
        self.my_answer.setTextFormat(QtCore.Qt.AutoText)
        self.my_answer.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.my_answer.setObjectName("my_answer")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(10, 180, 91, 41))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_1.setFont(font)
        self.label_1.setTextFormat(QtCore.Qt.AutoText)
        self.label_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 180, 91, 41))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.real_answer = QtWidgets.QLabel(self.centralwidget)
        self.real_answer.setGeometry(QtCore.QRect(200, 180, 21, 41))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.real_answer.setFont(font)
        self.real_answer.setTextFormat(QtCore.Qt.AutoText)
        self.real_answer.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.real_answer.setObjectName("real_answer")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 220, 1311, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 160, 1311, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 530, 1311, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.sel_num_1 = QtWidgets.QLabel(self.centralwidget)
        self.sel_num_1.setGeometry(QtCore.QRect(10, 240, 41, 61))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.sel_num_1.setFont(font)
        self.sel_num_1.setTextFormat(QtCore.Qt.AutoText)
        self.sel_num_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sel_num_1.setObjectName("sel_num_1")
        self.question_1 = QtWidgets.QLabel(self.centralwidget)
        self.question_1.setGeometry(QtCore.QRect(50, 230, 1251, 81))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.question_1.setFont(font)
        self.question_1.setTextFormat(QtCore.Qt.AutoText)
        self.question_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.question_1.setObjectName("question_1")
        self.question_4 = QtWidgets.QLabel(self.centralwidget)
        self.question_4.setGeometry(QtCore.QRect(10, 530, 1251, 261))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.question_4.setFont(font)
        self.question_4.setTextFormat(QtCore.Qt.AutoText)
        self.question_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.question_4.setObjectName("question_4")
        self.sel_num_2 = QtWidgets.QLabel(self.centralwidget)
        self.sel_num_2.setGeometry(QtCore.QRect(10, 340, 41, 61))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.sel_num_2.setFont(font)
        self.sel_num_2.setTextFormat(QtCore.Qt.AutoText)
        self.sel_num_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sel_num_2.setObjectName("sel_num_2")
        self.sel_num_3 = QtWidgets.QLabel(self.centralwidget)
        self.sel_num_3.setGeometry(QtCore.QRect(10, 440, 41, 61))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.sel_num_3.setFont(font)
        self.sel_num_3.setTextFormat(QtCore.Qt.AutoText)
        self.sel_num_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sel_num_3.setObjectName("sel_num_3")
        self.question_2 = QtWidgets.QLabel(self.centralwidget)
        self.question_2.setGeometry(QtCore.QRect(50, 330, 1251, 81))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.question_2.setFont(font)
        self.question_2.setTextFormat(QtCore.Qt.AutoText)
        self.question_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.question_2.setObjectName("question_2")
        self.question_3 = QtWidgets.QLabel(self.centralwidget)
        self.question_3.setGeometry(QtCore.QRect(50, 430, 1251, 81))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.question_3.setFont(font)
        self.question_3.setTextFormat(QtCore.Qt.AutoText)
        self.question_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.question_3.setObjectName("question_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "정보 보안 교육 프로그램"))
        self.sol_q.setText(_translate("MainWindow", "여기에 문제 들어가야함\n"
"여기에 문제 들어가야함"))
        self.my_answer.setText(_translate("MainWindow", "1"))
        self.label_1.setText(_translate("MainWindow", "나의 답 :"))
        self.label_2.setText(_translate("MainWindow", "/ 정답 :"))
        self.real_answer.setText(_translate("MainWindow", "1"))
        self.sel_num_1.setText(_translate("MainWindow", "1."))
        self.question_1.setText(_translate("MainWindow", "문제 보기 들어가야 함"))
        self.question_4.setText(_translate("MainWindow", "문제 해설 들어가야 함\n"
"문제 해설 들어가야 함\n"
"문제 해설 들어가야 함\n"
"문제 해설 들어가야 함"))
        self.sel_num_2.setText(_translate("MainWindow", "2."))
        self.sel_num_3.setText(_translate("MainWindow", "3."))
        self.question_2.setText(_translate("MainWindow", "문제 보기 들어가야 함"))
        self.question_3.setText(_translate("MainWindow", "문제 보기 들어가야 함"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = quiz_solution()
    ui.quiz_solution_setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
